--1. RANK() same rank for ties- skip number: Rank employees within each department based on their Salary.
SELECT * , RANK() OVER(PARTITION BY Department_id ORDER BY Salary DESC) AS Salary_Rank FROM Employees;

--2. DENSE_RANK() same rank for ties - do not skip: Determine the top three performing customers based on orders placed in current month and assign a dense rank to them.
SELECT TOP 3 Customer_id, 
COUNT(*)  AS TotalOrders,  
DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS DenseRank 
FROM Orders 
WHERE MONTH(Order_date)=MONTH(GETDATE())
GROUP BY Customer_id;

--3.ROW_NUMBER() unique sequential number: Generate a query that includes the total number of orders for each customer, assigning a row number to each order within the customer's record.
SELECT Customer_id , Order_id,
ROW_NUMBER() OVER(PARTITION  BY Customer_id ORDER BY Order_date) as Row_num 
FROM Orders;

--4.Subquery with Insert, Edit, Delete, Update:
--a.Insert new records into a 'Promotions' table for any 5 products.
INSERT INTO Promotions (Product_id,Promotion_name,Start_date,End_date,DiscountAmount,Active)
SELECT TOP 5 
Product_id, 'New Offer',GETDATE(), DATEADD(DAY, 30, GETDATE()), 10, 1 
FROM Products;

SELECT * FROM Promotions;

--b.Trigger: Update the 'Products' table where the product’s order is placed more than thrice in the current 
--month to mark these product as 'Featured'.
CREATE TRIGGER trg_featureproduct
ON Orders
AFTER INSERT
AS
BEGIN 
UPDATE p
SET Featured = 1
FROM Products p
JOIN(
SELECT Product_id 
FROM Orders
WHERE MONTH(Order_date)=MONTH(GETDATE())
GROUP BY Product_id
HAVING COUNT(*)> 3
) x ON p.Product_id = x.Product_id
END;

INSERT INTO Orders (Product_id, Quantity, Customer_id, Promotion_id, Order_date, Price)
VALUES
(1,1,1,NULL,GETDATE(),50000),
(1,1,2,NULL,GETDATE(),50000),
(1,1,3,NULL,GETDATE(),50000),
(1,1,4,NULL,GETDATE(),50000);

INSERT INTO Orders(Product_id, Quantity, Customer_id, Order_date, Price)
VALUES
(3,1,1,GETDATE(),50000),
(3,1,2,GETDATE(),50000),
(3,1,3,GETDATE(),50000),
(3,1,4,GETDATE(),50000);

select * from Orders;

SELECT Product_id, Product_name, Featured
FROM Products;

--c.Ensure to delete any promotions created (Start_date) before last 6 months. 
BEGIN TRANSACTION;
DELETE FROM Promotions 
WHERE Start_date < DATEADD(MONTH ,-6 ,GETDATE());

SELECT * FROM Promotions;
ROLLBACK;

--5.Create a view that joins the 'Orders' and 'Customers' tables to display order details along with customer information.
CREATE VIEW vw_ordercutomer
AS
SELECT o.Order_id, c.First_name, c.Last_name, o.Price, o.Order_date
FROM Orders o
JOIN
Customers c 
ON o.Customer_id =c.Customer_id;

SELECT * FROM vw_ordercutomer;

--6.Build a complex view that joins multiple tables such as ‘Orders’, 'Products' to display detailed order data along with product information for last 3 months.
CREATE VIEW vw_orderproduct
AS
SELECT  o.Order_id,p.Product_name,o.Quantity,o.Price,o.Order_date
FROM Orders o
JOIN
Products p
ON o.Product_id = p.Product_id
WHERE
o.Order_date >= DATEADD(MONTH,-3,GETDATE());

SELECT * FROM vw_orderproduct;

--7. View with WITH CHECK OPTION: Implement a view that shows employee salaries and allows for salary updates.
--Utilize the 'WITH CHECK OPTION' to ensure that salary must be > 10000.
CREATE  OR ALTER VIEW vw_Employeesalary
AS
SELECT * FROM Employees WHERE Salary>50000
WITH CHECK OPTION;

SELECT * FROM vw_Employeesalary;
SELECT * FROM Employees;

UPDATE vw_Employeesalary
SET Salary = 52000
WHERE Employee_id = 4;


--8.User-defined Functions: Develop a function that calculates the total cost of an 
--order based on the quantity and unit price of each product.
CREATE FUNCTION TotalCost(
@qty INT , @price DECIMAL(10,2))
RETURNS DECIMAL(10,2)
AS
BEGIN
RETURN (@qty * @price);
END;

SELECT    
Order_id,
Quantity,
Price, dbo.TotalCost(Quantity, Price)
AS TotalCost from Orders;

--10. Cursor: Write a cursor to iterate through a ‘Order’ ’table and calculate the
--total revenue generated by each product category. Display the results and insert them in a separate summary table
DECLARE @cat NVARCHAR(100), @rev DECIMAL(12,2);

DECLARE cur CURSOR FOR
SELECT p.Category_name, SUM(o.Price)
FROM Orders o
JOIN Products p ON o.Product_id=p.Product_id
GROUP BY p.Category_name;

OPEN cur;
FETCH NEXT FROM cur INTO @cat,@rev;

WHILE @@FETCH_STATUS=0
BEGIN
INSERT INTO Category_Summary(Category_name,Revenue)
VALUES(@cat,@rev);

PRINT @cat + ' ' + CAST(@rev AS NVARCHAR);

FETCH NEXT FROM cur INTO @cat,@rev;
END

CLOSE cur;
DEALLOCATE cur;

select * from Category_Summary;